flag_value {
    package: "com.android.system.virtualmachine.flags"
    name: "enable_vendor_modules"
    state: ifelse(release_avf_enable_vendor_modules, `true', `ENABLED', `DISABLED')
    permission: READ_ONLY
}
